[package]
name = "our_package"
version = "0.1.0"
edition = "2024"

[dependencies]
base64 = "0.13.0"
rand = "0.8.4"
rsa = "0.5.0"

[[bin]]
name = "our_package"
path = "src/main.rs"

[lib]
name = "our_package"
path = "src/lib.rs"
